# frozen_string_literal: true
source 'https://rubygems.org'

# Gems used by the dummy application
gem 'bootstrap', '~> 4.4'
gem 'jquery-rails'
gem 'rails'
gem 'sass-rails'
gem 'simple_form'
gem 'sprockets-rails'
gem 'sqlite3'
gem 'font-awesome-sass'
gem 'image_processing'

# Development dependencies
gem 'puma'
gem 'capybara'
gem 'database_cleaner'
gem 'factory_bot'
gem 'poltergeist'
gem 'pry-rails'
gem 'rspec-rails'
gem 'rubocop'
gem 'sham_rack', require: false
gem 'mini_magick'
gem 'selenium-webdriver'